name: Build ZK Ledger
on: [push] # Runs every time you upload code

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup update stable

      - name: Build Project
        run: cargo build --release

      - name: Upload the .exe for my friend
        uses: actions/upload-artifact@v4
        with:
          name: health-ledger-windows
          path: target/release/*.exe
